Title: EarnSmart
url: "https://sheroz255.github.io"
baseurl: "/my-earning-blog"
description: "Global Wealth Intelligence & AI Tools 2026"

plugins:
  - jekyll-sitemap

markdown: kramdown
theme: minima
